export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const GET_VIDEOGAME_DETAIL = "GET_VIDEOGAME_DETAIL";
export const GET_VIDEOGAMES_NAME = "GET_VIDEOGAMES_NAME";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const GET_GENRES = "GET_GENRES";
export const ADD_FAV = "ADD_FAV";
export const DELETE_FAV = "DELETE_FAV";
export const GET_FAV_BY_USERID = "GET_FAV_BY_USERID";
